version: '3.9'

services:
  microhost:
    build: .
    container_name: microhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www:rw
      - ./ssl:/etc/apache2/ssl:rw
      - ./conf/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./conf/a.hu.conf:/etc/apache2/sites-available/a.hu.conf
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: test
    depends_on:
      - db
